name: munchmap_prototype
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  dio: ^5.3.4
  flutter_polyline_points: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#FF2215"
  image: "assets/images/munchmap.png"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/munchmap.png"


flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/


